name: CI
on:
  push:
    branches:
      - main
      - fix-release
  pull_request:
    branches:
      - main

jobs:
  tests:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - name: Install Deps & Run Tests
        run: yarn install --frozen-lockfile && yarn test:ci

  release:
    # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
      - run: cat .npmrc
      # - name: Install Dependencies
      #   run: yarn install --frozen-lockfile
      # - name: Create Release Pull Request or Publish to npm
      #   uses: changesets/action@v1
      #   with:
      #     publish: yarn release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
